from prompt import *

PROMPTS = {
    "GENERAL" : GENERAL_PROMPT,
    "HR": HR_PROMPT,
    "INTERVIEW": INTERVIEW_PROMPT,
    "CUSTOMER_SUPPORT": CUSTOMER_SUPPORT_PROMPT,
    "COMPLAINT": CUSTOMER_SUPPORT_PROMPT,
    "SALES": SALES_PROMPT,
    "LEAVE_REQUEST": LEAVE_REQUEST_PROMPT
}

def get_prompt(category):
    return PROMPTS.get(category,GENERAL_PROMPT)